import {Product, Category, Alert, UserProfile, PricePoint} from '../types';

const generatePriceHistory = (
  basePrice: number,
  volatility: number = 0.15,
): PricePoint[] => {
  const points: PricePoint[] = [];
  const now = new Date();
  let price = basePrice * (1 + volatility * 0.5);

  for (let i = 29; i >= 0; i--) {
    const date = new Date(now);
    date.setDate(date.getDate() - i);
    const change = (Math.random() - 0.5) * 2 * volatility * basePrice * 0.1;
    price = Math.max(basePrice * 0.7, Math.min(basePrice * 1.5, price + change));
    points.push({
      date: date.toISOString().split('T')[0],
      price: Math.round(price),
    });
  }

  return points;
};

export const mockProducts: Product[] = [
  {
    id: '1',
    title: 'Беспроводные наушники TWS Pro',
    image: 'https://placeholder.com/300x300/electronics/headphones.png',
    currentPrice: 2490,
    oldPrice: 4990,
    discount: 50,
    category: 'electronics',
    marketplace: 'WB',
    priceHistory: generatePriceHistory(2490),
    rating: 4.7,
    reviewsSummary: 'Отличный звук, хорошая шумоизоляция, батарея держит 6 часов',
    affiliateUrl: 'https://www.wildberries.ru/catalog/1/detail.aspx',
  },
  {
    id: '2',
    title: 'Робот-пылесос Xiaomi Mi Robot Vacuum',
    image: 'https://placeholder.com/300x300/electronics/vacuum.png',
    currentPrice: 15990,
    oldPrice: 24990,
    discount: 36,
    category: 'electronics',
    marketplace: 'Ozon',
    priceHistory: generatePriceHistory(15990),
    rating: 4.8,
    reviewsSummary: 'Мощная уборка, тихий, хорошая навигация по квартире',
    affiliateUrl: 'https://www.ozon.ru/product/2',
  },
  {
    id: '3',
    title: 'Кроссовки Nike Air Max 270',
    image: 'https://placeholder.com/300x300/clothing/shoes.png',
    currentPrice: 7990,
    oldPrice: 12990,
    discount: 38,
    category: 'clothing',
    marketplace: 'WB',
    priceHistory: generatePriceHistory(7990),
    rating: 4.6,
    reviewsSummary: 'Удобные, легкие, размер соответствует. Подошва мягкая',
    affiliateUrl: 'https://www.wildberries.ru/catalog/3/detail.aspx',
  },
  {
    id: '4',
    title: 'Умная колонка Яндекс Станция Мини',
    image: 'https://placeholder.com/300x300/electronics/speaker.png',
    currentPrice: 4990,
    oldPrice: 7990,
    discount: 37,
    category: 'electronics',
    marketplace: 'Ozon',
    priceHistory: generatePriceHistory(4990),
    rating: 4.5,
    reviewsSummary: 'Хороший звук для своего размера, Алиса работает отлично',
    affiliateUrl: 'https://www.ozon.ru/product/4',
  },
  {
    id: '5',
    title: 'Куртка зимняя мужская Columbia',
    image: 'https://placeholder.com/300x300/clothing/jacket.png',
    currentPrice: 8990,
    oldPrice: 15990,
    discount: 44,
    category: 'clothing',
    marketplace: 'WB',
    priceHistory: generatePriceHistory(8990),
    rating: 4.4,
    reviewsSummary: 'Теплая, легкая, не продувается. Размер чуть большемерит',
    affiliateUrl: 'https://www.wildberries.ru/catalog/5/detail.aspx',
  },
  {
    id: '6',
    title: 'Набор постельного белья сатин',
    image: 'https://placeholder.com/300x300/home/bedding.png',
    currentPrice: 2290,
    oldPrice: 4590,
    discount: 50,
    category: 'home',
    marketplace: 'Ozon',
    priceHistory: generatePriceHistory(2290),
    rating: 4.3,
    reviewsSummary: 'Приятная ткань, не линяет после стирки, яркие цвета',
    affiliateUrl: 'https://www.ozon.ru/product/6',
  },
  {
    id: '7',
    title: 'Конструктор LEGO Technic',
    image: 'https://placeholder.com/300x300/kids/lego.png',
    currentPrice: 3490,
    oldPrice: 5990,
    discount: 42,
    category: 'kids',
    marketplace: 'WB',
    priceHistory: generatePriceHistory(3490),
    rating: 4.9,
    reviewsSummary: 'Интересный набор, ребенок в восторге. Качество деталей отличное',
    affiliateUrl: 'https://www.wildberries.ru/catalog/7/detail.aspx',
  },
  {
    id: '8',
    title: 'Крем для лица увлажняющий La Roche-Posay',
    image: 'https://placeholder.com/300x300/beauty/cream.png',
    currentPrice: 1290,
    oldPrice: 1990,
    discount: 35,
    category: 'beauty',
    marketplace: 'Ozon',
    priceHistory: generatePriceHistory(1290),
    rating: 4.7,
    reviewsSummary: 'Хорошо увлажняет, не вызывает аллергии, экономичный расход',
    affiliateUrl: 'https://www.ozon.ru/product/8',
  },
  {
    id: '9',
    title: 'Гантели разборные 2x10 кг',
    image: 'https://placeholder.com/300x300/sport/dumbbells.png',
    currentPrice: 3990,
    oldPrice: 6490,
    discount: 39,
    category: 'sport',
    marketplace: 'WB',
    priceHistory: generatePriceHistory(3990),
    rating: 4.5,
    reviewsSummary: 'Удобный хват, качественное покрытие, не пахнут резиной',
    affiliateUrl: 'https://www.wildberries.ru/catalog/9/detail.aspx',
  },
  {
    id: '10',
    title: 'Видеорегистратор Xiaomi 70mai',
    image: 'https://placeholder.com/300x300/auto/dashcam.png',
    currentPrice: 4490,
    oldPrice: 6990,
    discount: 36,
    category: 'auto',
    marketplace: 'Ozon',
    priceHistory: generatePriceHistory(4490),
    rating: 4.6,
    reviewsSummary: 'Четкая картинка днем и ночью, простая установка',
    affiliateUrl: 'https://www.ozon.ru/product/10',
  },
  {
    id: '11',
    title: 'Корм для кошек Royal Canin 4 кг',
    image: 'https://placeholder.com/300x300/pets/catfood.png',
    currentPrice: 2190,
    oldPrice: 3290,
    discount: 33,
    category: 'pets',
    marketplace: 'WB',
    priceHistory: generatePriceHistory(2190),
    rating: 4.8,
    reviewsSummary: 'Кошка ест с удовольствием, шерсть стала лучше',
    affiliateUrl: 'https://www.wildberries.ru/catalog/11/detail.aspx',
  },
  {
    id: '12',
    title: 'Смартфон Samsung Galaxy A54',
    image: 'https://placeholder.com/300x300/electronics/phone.png',
    currentPrice: 24990,
    oldPrice: 34990,
    discount: 29,
    category: 'electronics',
    marketplace: 'Ozon',
    priceHistory: generatePriceHistory(24990),
    rating: 4.5,
    reviewsSummary: 'Хорошая камера, быстрый процессор, батарея на 2 дня',
    affiliateUrl: 'https://www.ozon.ru/product/12',
  },
  {
    id: '13',
    title: 'Платье летнее женское миди',
    image: 'https://placeholder.com/300x300/clothing/dress.png',
    currentPrice: 1790,
    oldPrice: 3490,
    discount: 49,
    category: 'clothing',
    marketplace: 'WB',
    priceHistory: generatePriceHistory(1790),
    rating: 4.2,
    reviewsSummary: 'Красивый цвет, приятная ткань, но размер маломерит',
    affiliateUrl: 'https://www.wildberries.ru/catalog/13/detail.aspx',
  },
  {
    id: '14',
    title: 'Кофемашина DeLonghi Magnifica',
    image: 'https://placeholder.com/300x300/home/coffee.png',
    currentPrice: 32990,
    oldPrice: 49990,
    discount: 34,
    category: 'home',
    marketplace: 'Ozon',
    priceHistory: generatePriceHistory(32990),
    rating: 4.8,
    reviewsSummary: 'Варит отличный кофе, тихая, легко чистить',
    affiliateUrl: 'https://www.ozon.ru/product/14',
  },
  {
    id: '15',
    title: 'Детский самокат Micro Maxi',
    image: 'https://placeholder.com/300x300/kids/scooter.png',
    currentPrice: 5990,
    oldPrice: 8990,
    discount: 33,
    category: 'kids',
    marketplace: 'WB',
    priceHistory: generatePriceHistory(5990),
    rating: 4.7,
    reviewsSummary: 'Прочный, устойчивый, ребенку 5 лет очень нравится',
    affiliateUrl: 'https://www.wildberries.ru/catalog/15/detail.aspx',
  },
  {
    id: '16',
    title: 'Парфюмерная вода Dior Sauvage 100мл',
    image: 'https://placeholder.com/300x300/beauty/perfume.png',
    currentPrice: 6490,
    oldPrice: 9990,
    discount: 35,
    category: 'beauty',
    marketplace: 'Ozon',
    priceHistory: generatePriceHistory(6490),
    rating: 4.9,
    reviewsSummary: 'Стойкий аромат, шлейф на весь день, оригинал',
    affiliateUrl: 'https://www.ozon.ru/product/16',
  },
  {
    id: '17',
    title: 'Беговая дорожка электрическая',
    image: 'https://placeholder.com/300x300/sport/treadmill.png',
    currentPrice: 19990,
    oldPrice: 34990,
    discount: 43,
    category: 'sport',
    marketplace: 'WB',
    priceHistory: generatePriceHistory(19990),
    rating: 4.4,
    reviewsSummary: 'Компактная, тихая, скорость до 12 км/ч, хорошая амортизация',
    affiliateUrl: 'https://www.wildberries.ru/catalog/17/detail.aspx',
  },
  {
    id: '18',
    title: 'Автомобильные шины Michelin R17',
    image: 'https://placeholder.com/300x300/auto/tires.png',
    currentPrice: 7490,
    oldPrice: 11990,
    discount: 38,
    category: 'auto',
    marketplace: 'Ozon',
    priceHistory: generatePriceHistory(7490),
    rating: 4.6,
    reviewsSummary: 'Отличное сцепление, тихие, износостойкие',
    affiliateUrl: 'https://www.ozon.ru/product/18',
  },
  {
    id: '19',
    title: 'Лежанка для собак ортопедическая L',
    image: 'https://placeholder.com/300x300/pets/dogbed.png',
    currentPrice: 2990,
    oldPrice: 4990,
    discount: 40,
    category: 'pets',
    marketplace: 'WB',
    priceHistory: generatePriceHistory(2990),
    rating: 4.5,
    reviewsSummary: 'Собака сразу облюбовала, чехол снимается для стирки',
    affiliateUrl: 'https://www.wildberries.ru/catalog/19/detail.aspx',
  },
  {
    id: '20',
    title: 'Планшет Apple iPad 10.2 64GB',
    image: 'https://placeholder.com/300x300/electronics/tablet.png',
    currentPrice: 29990,
    oldPrice: 39990,
    discount: 25,
    category: 'electronics',
    marketplace: 'Ozon',
    priceHistory: generatePriceHistory(29990),
    rating: 4.9,
    reviewsSummary: 'Быстрый, отличный экран, батарея на целый день',
    affiliateUrl: 'https://www.ozon.ru/product/20',
  },
  {
    id: '21',
    title: 'Рюкзак городской водонепроницаемый',
    image: 'https://placeholder.com/300x300/clothing/backpack.png',
    currentPrice: 1990,
    oldPrice: 3490,
    discount: 43,
    category: 'clothing',
    marketplace: 'WB',
    priceHistory: generatePriceHistory(1990),
    rating: 4.3,
    reviewsSummary: 'Вместительный, удобные лямки, есть отсек для ноутбука',
    affiliateUrl: 'https://www.wildberries.ru/catalog/21/detail.aspx',
  },
  {
    id: '22',
    title: 'Мультиварка Redmond RMC-M90',
    image: 'https://placeholder.com/300x300/home/multicooker.png',
    currentPrice: 4990,
    oldPrice: 7990,
    discount: 38,
    category: 'home',
    marketplace: 'Ozon',
    priceHistory: generatePriceHistory(4990),
    rating: 4.6,
    reviewsSummary: 'Готовит отлично, много программ, легко мыть',
    affiliateUrl: 'https://www.ozon.ru/product/22',
  },
  {
    id: '23',
    title: 'Фитнес-браслет Xiaomi Mi Band 8',
    image: 'https://placeholder.com/300x300/electronics/band.png',
    currentPrice: 2790,
    oldPrice: 3990,
    discount: 30,
    category: 'electronics',
    marketplace: 'WB',
    priceHistory: generatePriceHistory(2790),
    rating: 4.7,
    reviewsSummary: 'Яркий экран, точный пульсометр, батарея на 2 недели',
    affiliateUrl: 'https://www.wildberries.ru/catalog/23/detail.aspx',
  },
  {
    id: '24',
    title: 'Коляска детская прогулочная Babyzen',
    image: 'https://placeholder.com/300x300/kids/stroller.png',
    currentPrice: 18990,
    oldPrice: 29990,
    discount: 37,
    category: 'kids',
    marketplace: 'Ozon',
    priceHistory: generatePriceHistory(18990),
    rating: 4.8,
    reviewsSummary: 'Легкая, компактно складывается, отличная проходимость',
    affiliateUrl: 'https://www.ozon.ru/product/24',
  },
];

export const mockCategories: Category[] = [
  {id: 'electronics', name: 'Электроника', icon: 'laptop', productCount: 156},
  {id: 'clothing', name: 'Одежда', icon: 'tshirt-crew', productCount: 243},
  {id: 'home', name: 'Дом и сад', icon: 'home', productCount: 189},
  {id: 'kids', name: 'Детское', icon: 'baby-carriage', productCount: 97},
  {id: 'beauty', name: 'Красота', icon: 'face-woman', productCount: 134},
  {id: 'sport', name: 'Спорт', icon: 'dumbbell', productCount: 78},
  {id: 'auto', name: 'Авто', icon: 'car', productCount: 112},
  {id: 'pets', name: 'Животные', icon: 'paw', productCount: 65},
];

export const mockAlerts: Alert[] = [
  {
    id: 'alert-1',
    keyword: 'наушники TWS',
    maxPrice: 3000,
    category: 'electronics',
    active: true,
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'alert-2',
    keyword: 'кроссовки Nike',
    maxPrice: 8000,
    category: 'clothing',
    active: true,
    createdAt: '2024-01-20T14:30:00Z',
  },
  {
    id: 'alert-3',
    keyword: 'робот-пылесос',
    maxPrice: 20000,
    category: 'electronics',
    active: false,
    createdAt: '2024-02-01T09:15:00Z',
  },
  {
    id: 'alert-4',
    keyword: 'LEGO',
    maxPrice: 5000,
    category: 'kids',
    active: true,
    createdAt: '2024-02-10T16:45:00Z',
  },
  {
    id: 'alert-5',
    keyword: 'корм для кошек',
    maxPrice: 2500,
    category: 'pets',
    active: true,
    createdAt: '2024-02-15T11:20:00Z',
  },
  {
    id: 'alert-6',
    keyword: 'iPad',
    maxPrice: 35000,
    category: 'electronics',
    active: true,
    createdAt: '2024-03-01T08:00:00Z',
  },
];

export const mockUserProfile: UserProfile = {
  id: 'user-1',
  name: 'Александр',
  email: 'alex@example.com',
  subscription: 'vip',
  referralCode: 'ALEX2024',
  totalSaved: 47850,
  dealsTracked: 156,
  bestDeal: 70,
};
